apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: shop-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: shop # ресурс относится ко всей системе shop
spec:
  replicas: {{ .Values.api.instances }}
  selector:
    matchLabels:
      app.kubernetes.io/name: shop-api
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/part-of: shop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shop-api
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: shop # ресурс относится ко всей системе shop
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.version }}}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          resources:
            {{ toYaml .Values.api.resources | nindent 12 }}

          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
          readinessProbe: # параметры для readiness-пробы
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe: # параметры для liveness-пробы
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10