apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app.kubernetes.io/name: shop-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: shop # ресурс относится ко всей системе shop
spec:
  replicas: {{ .Values.worker.instances }}
  selector:
    matchLabels:
      app.kubernetes.io/name: shop-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/part-of: shop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shop-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: shop # ресурс относится ко всей системе shop
    spec:
      initContainers: # проверяем, применены ли изменения к схеме данных; до окончания их применения не запускаем приложение
        - name: wait-for-schema-migrations
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.version }}"
          imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
          args:
            - "-connectRetries=60"
            - "validate"
          env:
            - name: FLYWAY_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-app
                  key: jdbc-uri
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-app
                  key: username

            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-app
                  key: password
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.version }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          resources:
            {{ toYaml .Values.worker.resources | nindent 12 }}

          ## Параметры подключения приложения к базе данных
          env:
            - name: DB_URL # JDBC-адрес PostgreSQL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-app
                  key: jdbc-uri

            - name: DB_USER # пользователь базы
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-app
                  key: username

            - name: DB_PASSWORD # пароль пользователя базы
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-app
                  key: password

          ports:
            - name: http
              containerPort: {{ .Values.worker.service.port }}
          readinessProbe: # параметры для readiness-пробы
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe: # параметры для liveness-пробы
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10