apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app.kubernetes.io/name: shop-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.worker.service.type }}
  selector:
    app.kubernetes.io/name: shop-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.worker.service.port }}
      targetPort: http
      {{- if eq .Values.worker.service.type "NodePort" }}
      nodePort: {{ .Values.worker.service.nodePort }}
      {{- end }}
