image:
  repository: lab2-api
  tag: "1.0"
  pullPolicy: IfNotPresent

logs:
  collect: true

service:
  type: NodePort
  port: 8080 # порт внутри контейнера
  nodePort: 30080 # порт сервиса, куда необходимо слать запросы к приложению
