{{- if .Values.monitoring.prometheusOperator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-services
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: shop
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}